name = "TRGKit"
uuid = "7dfc3ef0-df9b-475f-b8e2-b91f34f5d84d"
authors = ["victor <victor.vanthilt@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
Revise = "3.6.4"
TensorKit = "0.13.2"
